# Generated by Django 2.2.5 on 2019-10-09 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apellidos', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=20)),
                ('Hospital', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nutriologos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apellidos', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=20)),
                ('Clinica', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apellidos', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=20)),
                ('Fechanacimiento', models.DateField()),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='NumID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('Doctores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondeusuarios.Doctores')),
                ('Nutriologos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondeusuarios.Nutriologos')),
            ],
        ),
    ]
