# Generated by Django 2.2.5 on 2019-10-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondeusuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numid',
            name='Doctores',
        ),
        migrations.RemoveField(
            model_name='numid',
            name='Nutriologos',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.DeleteModel(
            name='Doctores',
        ),
        migrations.DeleteModel(
            name='NumID',
        ),
        migrations.DeleteModel(
            name='Nutriologos',
        ),
    ]
