# Generated by Django 2.2.5 on 2019-10-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondeusuarios', '0003_doctores_numid_nutriologos_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numid',
            old_name='Dotores',
            new_name='Doctores',
        ),
    ]
