# Generated by Django 2.2.5 on 2019-10-12 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestiondeusuarios', '0005_auto_20191011_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellidos', models.CharField(max_length=20)),
                ('Hospital', models.CharField(max_length=20)),
                ('Cedula', models.PositiveIntegerField()),
                ('Telefono', models.PositiveIntegerField()),
                ('Correo', models.TextField()),
                ('Foto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nutriologos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellidos', models.CharField(max_length=20)),
                ('Institucion', models.CharField(max_length=20)),
                ('Cedula', models.PositiveIntegerField()),
                ('Telefono', models.PositiveIntegerField()),
                ('Correo', models.TextField()),
                ('Foto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellidos', models.CharField(max_length=20)),
                ('Fechanacimiento', models.DateField()),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('Peso', models.PositiveSmallIntegerField()),
                ('Estatura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Tipodesangre', models.CharField(choices=[('A', 'A+'), ('B', 'A-'), ('C', 'B+'), ('D', 'B-'), ('E', 'AB+'), ('F', 'AB-'), ('G', 'O+'), ('H', 'O-')], default='G', max_length=1)),
                ('Observaciones', models.CharField(max_length=500)),
                ('Foto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NumID',
            fields=[
                ('IDnumber', models.AutoField(primary_key=True, serialize=False)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('Doctores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondeusuarios.Doctores')),
                ('Nutriologos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondeusuarios.Nutriologos')),
                ('Usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondeusuarios.Usuarios')),
            ],
        ),
    ]
