# Generated by Django 2.2.5 on 2019-10-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondeusuarios', '0006_doctores_numid_nutriologos_usuarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctores',
            new_name='Doctor',
        ),
        migrations.RenameModel(
            old_name='Nutriologos',
            new_name='Nutriologo',
        ),
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
