# Generated by Django 2.2.5 on 2019-10-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondeusuarios', '0007_auto_20191012_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numid',
            old_name='Doctores',
            new_name='Doctor',
        ),
        migrations.RenameField(
            model_name='numid',
            old_name='Nutriologos',
            new_name='Nutriologo',
        ),
        migrations.RenameField(
            model_name='numid',
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
